import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className="flex items-center justify-center h-screen w-screen m-0 text-black bg-white"> */}
      <body className="bg-stone-300 bg-gradient-radial from-black from-10% via-transparent via-11% bg-[length:15px_15px] bg-repeat overflow-hidden">{children}</body>
    </html>
  );
}
